#!/usr/bin/env python3
"""Validate and render the report produced by live platform contract tests."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REQUIRED = ("tikTok", "instagram", "x", "reddit", "bluesky", "pinterest", "snapchat", "kick", "threads", "tumblr", "imgur")
ALL = REQUIRED + ("youTube", "directMedia")
VALID = {"passing", "limited", "needsCredential", "failing", "blocked", "notShipped"}
# A source that can be captured, even partially, satisfies a release gate. Only a source
# that fails or is blocked does not.
RELEASE_ACCEPTABLE = {"passing", "limited", "needsCredential"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("report", type=Path)
    parser.add_argument("--markdown", type=Path)
    parser.add_argument("--release", action="store_true", help="Require every release-gated platform to pass.")
    parser.add_argument("--require-passing", action="append", default=[], metavar="PLATFORM", help="Require a named platform to pass.")
    arguments = parser.parse_args()

    if not arguments.report.is_file():
        raise SystemExit(f"Missing platform support report: {arguments.report}")
    try:
        value = json.loads(arguments.report.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise SystemExit(f"Invalid support report JSON: {error}") from error

    entries = value.get("platforms", value if isinstance(value, list) else None)
    if not isinstance(entries, list):
        raise SystemExit("Support report must contain a 'platforms' array.")
    by_platform = {}
    for entry in entries:
        if not isinstance(entry, dict):
            raise SystemExit("Each support-report entry must be an object.")
        platform = entry.get("platform")
        status = entry.get("status")
        evidence = entry.get("evidence")
        if platform not in ALL:
            raise SystemExit(f"Unexpected platform in support report: {platform!r}")
        if platform in by_platform:
            raise SystemExit(f"Duplicate platform in support report: {platform}")
        if status not in VALID:
            raise SystemExit(f"Invalid status for {platform}: {status!r}")
        if not isinstance(evidence, str) or not evidence.strip():
            raise SystemExit(f"Missing evidence for {platform}")
        by_platform[platform] = entry

    missing = [platform for platform in ALL if platform not in by_platform]
    if missing:
        raise SystemExit("Support report omitted: " + ", ".join(missing))
    if arguments.release:
        failures = [platform for platform in REQUIRED if by_platform[platform]["status"] not in RELEASE_ACCEPTABLE]
        if failures:
            raise SystemExit("Required platform contracts are not passing: " + ", ".join(failures))
    required_passing = []
    for platform in arguments.require_passing:
        if platform not in ALL:
            raise SystemExit(f"Unknown required-passing platform: {platform}")
        if by_platform[platform]["status"] != "passing":
            required_passing.append(platform)
    if required_passing:
        raise SystemExit("Expected passing platform contract(s): " + ", ".join(required_passing))

    if arguments.markdown:
        rows = ["# Platform support report", "", "Generated by live contract tests. A platform is shown as shipped only when its status is `passing`.", "", "| Platform | Status | Evidence |", "| --- | --- | --- |"]
        for platform in ALL:
            entry = by_platform[platform]
            evidence = entry["evidence"].replace("|", "\\|")
            rows.append(f"| {platform} | {entry['status']} | {evidence} |")
        arguments.markdown.parent.mkdir(parents=True, exist_ok=True)
        arguments.markdown.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
